### ISSUE TITLE
Ingress Nginx backend support

### ISSUE THREAD

**Issue by onedr0p** [tarampampam/error-pages#11]
Thanks for making these! I am wondering if it's all possible to support a default backend when using [ingress-nginx](https://kubernetes.github.io/ingress-nginx/). 

When using ingress-nginx in kubernetes you can set a `defaultBackend`

https://github.com/kubernetes/ingress-nginx/blob/f5cfd5730c4b296c87fbc531c83a6e4f33483b75/charts/ingress-nginx/values.yaml#L605

an example of a default backend is below, using Go is not a hard requirement. It just acts on HTTP headers as described in the table on this project.

https://github.com/181192/custom-error-pages

I totally get not wanting to support this, but I'd rather have it built in here instead of forking your repo.

Thanks!

**Comment by tarampampam** [comment]
Hi @onedr0p!

Can you make a PR with the required changes? Currently, I have no experience with k8s and don't have enough free time for learning.

**Comment by onedr0p** [comment]
The more I'm looking at this the more it's hard to integrate these two here. The default backend for nginx ingress is wildly different than here which is just serving static content.

I might fork the custom error pages repo I linked above and add these themes. I'll 110% add recognition to your project here for people using traefik :)
