### ISSUE TITLE
GDPR - Replace Google Fonts by Bunny Fonts

### ISSUE THREAD

**Issue by ToshY** [tarampampam/error-pages#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

Issue derived from discussion #129 

> After finding out that that serving fonts through Google Fonts is not GDPR compliant ([bunny.net](https://bunny.net/blog/bringing-privacy-back-into-your-own-hands-introducing-bunny-fonts/); [official ruling](https://rewis.io/urteile/urteil/lhm-20-01-2022-3-o-1749320/)), is it maybe an idea to update this in the templates by switching to another font service, like for example [Bunny Fonts](https://fonts.bunny.net/about)? It would be as easy as just replacing fonts.googleapis.com by fonts.bunny.net.

### Suggest a solution

Replace `fonts.googleapis.com` by `fonts.bunny.net` in link tags.

**Comment by tarampampam** [comment]
Thank you @ToshY!
