### ISSUE TITLE
Error pages middleware break other services

### ISSUE THREAD

**Issue by adlion** [tarampampam/error-pages#15]
Adding middleware to a service or middleware chain beaks whenever the error pages services is down.

To reproduce add the error pages middleware to a service and than stop the error pages service and try to access the other service.

There should be another way to catch this error pages but without breaking other services if error pages service goes down.

**Comment by tarampampam** [comment]
Hi @adlion! Looks like the https://github.com/traefik/traefik repository will be more relevant for your issue?

**Comment by tarampampam** [comment]
Closed due inactivity
