### ISSUE TITLE
Turn off logs

### ISSUE THREAD

**Issue by kfirfer** [tarampampam/error-pages#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

Trying to disable logs

### Suggest a solution

Have an env var to disable logs

**Comment by averon420** [comment]
yes please, I would also like that. In the meanwhile, is there any workaround for this? like modifying the config of the web server?

**Comment by tarampampam** [comment]
When I will have free time (this week, I hope) I have plans to rewrite the CLI part of this application and append the possibility to change the logging level.

**Comment by averon420** [comment]
> When I will have free time (this week, I hope) I have plans to rewrite the CLI part of this application and append the possibility to change the logging level.

awesome! thanks a lot :) can you leave a note here, when you found time?

**Comment by tarampampam** [comment]
Yes, sure!

**Comment by tarampampam** [comment]
Now you can use the flag `--log-level warn` or `--log-level error` to disable unimportant log messages.

:fire: Released in [v2.20.0](https://github.com/tarampampam/error-pages/releases/tag/v2.20.0)

**Comment by averon420** [comment]
> Now you can use the flag `--log-level warn` or `--log-level error` to disable unimportant log messages.
> 
> 🔥 Released in [v2.20.0](https://github.com/tarampampam/error-pages/releases/tag/v2.20.0)

awesome!! Thanks a lot :)
