### ISSUE TITLE
Gifs in readme

### ISSUE THREAD

**Issue by modem7** [tarampampam/error-pages#24]
Heya, 

Out of curiosity, how are you generating the gifs in the readme file?

Thanks!

**Comment by tarampampam** [comment]
[kazam](https://launchpad.net/kazam) + [ezgif.com/video-to-gif](https://ezgif.com/video-to-gif) 😃

**Comment by modem7** [comment]
Ahhah! Perfect! 

Thank you!

I'm loving your readme layout, so I wanted to basically clone how you did it to stay as close as possible to your project for the fork I've done.
