### ISSUE TITLE
cross origin request to fonts.bunny.net fails

### ISSUE THREAD

**Issue by Dark3clipse** [tarampampam/error-pages#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] And it has nothing to do with Traefik

### Describe the bug

I deployed error pages by building it in my docker image of openresty. I manage to get the error page ghost working. The only thing that fails for me is the loading of the font.

I get these error messages in console:
![image](https://github.com/tarampampam/error-pages/assets/5069005/fc45c29b-e07b-4fe7-a5fc-3252de1eec3b)

Do you know if there is anything I can do to make the font load properly?

**Comment by tarampampam** [comment]
Hello, and thanks for reporting the issue! Could you please provide the full set of HTTP headers from your server? It seems that a CORS header has been set, denying the loading of any external resources.
