### ISSUE TITLE
Docker Image for 2.27.0 failed to build

### ISSUE THREAD

**Issue by jathek** [tarampampam/error-pages#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] And it has nothing to do with Traefik

### Describe the bug

The docker image for 2.27.0 failed to build. Some sort of golang issue?

https://github.com/tarampampam/error-pages/actions/runs/8309184333

**Comment by tarampampam** [comment]
Thank you so much! No one can hide from you :) I've already made a [hotfix](c851aad4f2531d43fb76697d4e1c5f40501ba61b), recreated the tag, and released it. Now everything seems okay
