### ISSUE TITLE
Upgrade to 2.0.0 broke error-pages

### ISSUE THREAD

**Issue by onedr0p** [tarampampam/error-pages#29]
I am trying to upgrade to 2.0.0 of this docker image, great job re-writing it in Go!

I would have thought it would have been a seamless upgrade however on 2.0.0 I am getting the message. `Hi there! Error pages are available at the following URLs: /{code}.html`. If I rollback to 1.8.0 it works fine.

## 1.8.0 logs

```
error-pages-644fdd7c94-g5pzr error-pages 10.69.152.237 - - [05/Oct/2021:13:43:13 +0000] "GET / HTTP/1.1" 404 3526 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "x.x.x.x, 172.70.110.112"
```

## 2.0.0 logs

```
error-pages-6b4cc76777-4mt4l error-pages {"level":"info","ts":1633441272.6022592,"msg":"HTTP request processed","useragent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36","method":"GET","url":"/","status_code":404,"connection_close":false,"duration":0.000023755}
```

You can see my use of error-pages with the middleware and ingressroute here:
https://github.com/onedr0p/home-cluster/tree/main/cluster/apps/networking/error-pages

Is a requirement of the new version supposed to force us to annotate each ingress with using this middleware? If so, can that be changed to be global again?

Thanks!

**Comment by tarampampam** [comment]
Hi @onedr0p!

On the first version, the request with an empty URI returned code 200 with the text 404 error. I can bring this behavior back if required. Will this solve your problem?

**Comment by onedr0p** [comment]
That's would be excellent, thanks!
