### ISSUE TITLE
ADD_TEMPLATE env var

### ISSUE THREAD

**Issue by JohnLindahlTech** [tarampampam/error-pages#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

Trying out v3 in docker with `tarampampam/error-pages:3.1.0`

I have always been running a custom template and with the new version I need to run the cli flag `--add-template` and it makes the Docker-composefile a bit messy which was not needed prior.

### Suggest a solution

Adding a companion env var `ADD_TEMPLATE` as for the other config flags, would allow me to not override the default `command` in docker.

**Comment by tarampampam** [comment]
May I ask if there are any problems with the command overriding? Setting it to `serve --add-template /path/to/file` shouldn't be difficult, I suppose. Or am I mistaken?

**Comment by JohnLindahlTech** [comment]
Not difficult, more on the keeping things neat as I prefer config via env-vars. For visuals and easier to maintain I find it.

**Comment by tarampampam** [comment]
🚀 [v3.2.0](https://github.com/tarampampam/error-pages/releases/tag/v3.2.0)

**Comment by JohnLindahlTech** [comment]
Thank you very much!
