### ISSUE TITLE
docker-enrypoint.sh error creating existent directory

### ISSUE THREAD

**Issue by cinzas** [tarampampam/error-pages#3]
Hi

I have the following error when restarting the container after initial start.
```
error-pages           | mkdir: can't create directory '/opt/html/nginx-error-pages': File exists
error-pages           | /docker-entrypoint.sh: set pages for template 'ghost' as default (make accessible in root directory)

```

Solved by chaging docker-entrypoint.sh line 16, from
`  mkdir /opt/html/nginx-error-pages;`

to

`  mkdir -p /opt/html/nginx-error-pages;`

**Comment by tarampampam** [comment]
Hi!

Fixed and released: https://github.com/tarampampam/error-pages/releases/tag/v1.3.1
