### ISSUE TITLE
Fork github actions issue

### ISSUE THREAD

**Issue by modem7** [tarampampam/error-pages#37]
Heya, 

I thought I'd update my fork to the new version that you've released (doing a test on a different repo before committing to my actual fork rather than creating a branch for now) to keep it up to date and to add a couple more templates, and it seems that the github actions fail on build with the error:

`stat /home/runner/work/error-page-test/error-page-test/cmd/error-pages: directory not found`

https://github.com/modem7/error-page-test/runs/4361391755?check_suite_focus=true

Is this something you'd be willing to assist with or would this be something outside your remit? 

Many thanks!

**Comment by tarampampam** [comment]
Heya @modem7!

Looks like you forgot about the [`cmd` directory](https://github.com/tarampampam/error-pages/tree/master/cmd) :)

**Comment by modem7** [comment]
> Heya @modem7!
> 
> Looks like you forgot about the [`cmd` directory](https://github.com/tarampampam/error-pages/tree/master/cmd) :)

Weird! Didn't upload when I commited!

One day I'll actually have some coffee before doing things like this. 

Apologies for the ID10T and thank you very much!
