### ISSUE TITLE
http status code 200 instead 404

### ISSUE THREAD

**Issue by DanielRamp** [tarampampam/error-pages#41]
In the old version the **http status code from a not found site was 404 and now it's 200** (of course with the text being '404 not found').

I'm not sure if this is the correct behaviour in web, because even if we serve a custom status page, I think the status code should still be "the error" (e.g. 404).

Can someone tell me what I did wrong or if this is just the new behaviour?

If this is not the expected outcome, feel free to ask me any system details that are needed, as I'm not sure what is relevant. some listed here:
- reverse proxy: `traefik:v2.5`
- `tarampampam/error-pages:2.2.0`

&nbsp;

PS: Thanks for rewriting this cool project in golang. ✨

**Comment by tarampampam** [comment]
```
$ docker run --rm -d -p "8080:8080/tcp" tarampampam/error-pages

$ curl -v http://127.0.0.1:8080/foobar
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /foobar HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Wed, 29 Dec 2021 10:13:57 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 80
< 
* Connection #0 to host 127.0.0.1 left intact
Wrong request URL. Error pages are available at the following URLs: /{code}.html

$ curl -v http://127.0.0.1:8080/500.html
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /500.html HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 29 Dec 2021 10:14:46 GMT
< Content-Type: text/html; charset=utf-8
...
```

For the non-existing page status code is 404, for the error page with code 500 - the response code is 200. Should we change something? I think - no :)

**Comment by DanielRamp** [comment]
Did I understand you correctly, you want always http response code 200 even if these are error pages?


Because this new behaviour is not what I see as "normal" from big websites ([1], [2]) and also breaks for example a statuspage.
In previous versions of error-pages a statuspage could just request the page every minute or so and if the response http code is 200 it's "healthy/up".

[1]: https://www.google.com/404
[2]: https://www.microsoft.com/404


Or is there something I have to set in my reverse proxy (traefik) configuration to get this desired result back?

**Comment by tarampampam** [comment]
Oh, sorry, you're right... For the non-existing domains response code should be not 200. I have made a flag `--default-error-page`, but forgot about the response code customization. I will make a fix shortly, thanks for your issue!

**Comment by tarampampam** [comment]
Version [2.3.0](https://github.com/tarampampam/error-pages/releases/tag/v2.3.0) has been published! After updating all should be fine :) Feel free to close this issue after checking on your side.

**Comment by tarampampam** [comment]
@DanielRamp ping :)

**Comment by DanielRamp** [comment]
_Finally I was able to try it._

The default 404 for unknown/not existing domains works as expected.


_Also I'm sorry for not answering. I was really happy when I saw your comments but haven't had enough time to test it and give feedback, also didn't want to just write something like "cool, testing it soon..."_
