### ISSUE TITLE
ingress-nginx support

### ISSUE THREAD

**Issue by onedr0p** [tarampampam/error-pages#45]
Hi 👋🏼  It would be pretty neat to have your project support [ingress-nginx](https://kubernetes.github.io/ingress-nginx/), currently I've been using [181192/custom-error-pages](https://github.com/181192/custom-error-pages) which has some of your themes (there's credit to you in the README). However it would be awesome if your project was a solution for both traefik and ingress-nginx. Thanks!

Edit: This is a very basic implentation of the `default-backend` as provided by the ingress-nginx project.
https://github.com/kubernetes/ingress-nginx/tree/main/images/custom-error-pages/rootfs

**Comment by tarampampam** [comment]
Maybe we can do it together? :)

I can write a code (based on your specification), and you can write documentation/examples/charts in the readme file? I'm not lazy, really, I just have very little expertise with k8s...

**Comment by onedr0p** [comment]
That works for me!

**Comment by tarampampam** [comment]
@onedr0p Could you please check changes in the PR https://github.com/tarampampam/error-pages/pull/49 ? I hope you like them a lot :)

**Comment by tarampampam** [comment]
I'm still waiting for your checking 😜

**Comment by onedr0p** [comment]
Same image as before?

**Comment by tarampampam** [comment]
Yep

**Comment by onedr0p** [comment]
I am getting a xml response on a 404, this is because SHOW_DETAILS is set?

```xml
<error>
<code>404</code>
<message>Not Found</message>
<description>The server can not find the requested page</description>
<details>
<originalURI>/</originalURI>
<namespace/>
<ingressName/>
<serviceName/>
<servicePort/>
<requestID>9bc2cec5c9a85f3ec31b110af837c099</requestID>
<timestamp>1643290606</timestamp>
</details>
</error>```

**Comment by tarampampam** [comment]
The content-type detection method can be found here:

https://github.com/tarampampam/error-pages/blob/bed576f26cc1952baad93d3d9819dcd018a0ea51/internal/http/core/formats.go#L19-L46

So, xml format was requested using the `X-Format` or `Content-Type` header in your HTTP request, I think. Can you show to me more details?

**Comment by onedr0p** [comment]
I can see the request come into the pod when I hit something that 404s

```
ingress-nginx-defaultbackend-5cdd84b798-fzrhw ingress-nginx-default-backend {"level":"info","ts":1643296712.072719,"msg":"HTTP request processed","useragent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36","method":"GET","url":"/","referer":"","status_code":404,"connection_close":false,"duration":0.000760462}
```

But in my browser I see:

![image](https://user-images.githubusercontent.com/213795/151388401-eb4fc0be-7778-4f4a-8b30-e7de422709c1.png)

**Comment by onedr0p** [comment]
Appears the request headers contain both text and xml types 😕 

![image](https://user-images.githubusercontent.com/213795/151391171-7d46140e-d837-4542-98d2-825836dbc775.png)

**Comment by onedr0p** [comment]
Maybe some logic is needed to always use `text/html` if others are present?

**Comment by tarampampam** [comment]
> Appears the request headers contain both `text/html` and `application/xml` types 😕 
> 
> ![image](https://user-images.githubusercontent.com/213795/151391171-7d46140e-d837-4542-98d2-825836dbc775.png)

Headers `Content-Type` and `accept` are not same :) How to reproduce this with curl?

**Comment by onedr0p** [comment]
Whoops yep haha, for now you can see this in action at https://test.devbu.io

**Comment by onedr0p** [comment]
Beautiful that's my Cloudflare WAF in action haha

**Comment by tarampampam** [comment]
I see that all work as expected! Where is the problem in this case?

**Comment by onedr0p** [comment]
The problem seems to be...

Browser: returns XML error msg

CURL: returns html error msg

I am at a complete loss as to what is causing that behavior.

**Comment by tarampampam** [comment]
Could you please to make some additional tests? First of all, let's try to reproduce an error locally:

```
$ docker run --rm -p "8080:8080/tcp" -e "SHOW_DETAILD=true" tarampampam/error-pages:ingress-test
```

After that, open in your browser `http://127.0.0.1:8080` and make a request using curl: `$ curl -v http://127.0.0.1:8080`

Did you see the XML response in this case?

**Comment by onedr0p** [comment]
Yep, that looks fine here too. I think the issue might be related more to Kubernetes and the ingress-nginx helm chart. I'll write up an example how to test soon.

**Comment by onedr0p** [comment]
## Some pre-reqs:

```bash
# install k3d, kubectl, helm (or grab the binaries from github releases/AUR/whatever package manager)
brew install k3d kubectl helm

# Warning: k3d 5.2.2 is already installed and up-to-date.
# Warning: kubernetes-cli 1.23.3 is already installed and up-to-date.
# Warning: helm 3.8.0 is already installed and up-to-date.

# create simple cluster without traefik and expose port 30080 which ingress-nginx will use
k3d cluster create test --k3s-arg '--disable=traefik@server:0' -p "80:30080@server:0"

# verify you can see nodes
kubectl get nodes

# verify you can pods
kubectl get pods -A

# install ingress-nginx helm repository
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update
```

## Save following file as `ingress-nginx-values.yaml`

```yaml
controller:
  replicaCount: 1
  service:
    enabled: true
    type: NodePort
    nodePorts:
      http: 30080
  config:
    custom-http-errors: >-
      401,403,404,500,501,502,503
defaultBackend:
  enabled: true
  image:
    repository: docker.io/tarampampam/error-pages
    tag: ingress-test
    pullPolicy: Always
  extraEnvs:
    - name: TEMPLATE_NAME
      value: l7-dark
    - name: SHOW_DETAILS
      value: "true"
```

## Install ingress-nginx and test

```bash
helm install ingress-nginx --namespace kube-system --version "4.0.16" --values ./ingress-nginx-values.yaml ingress-nginx/ingress-nginx
```

## Go to your browser and see the XML

http://localhost:80

## Clean up k3d

```bash
k3d cluster delete test
```

**Comment by dennisdalsten** [comment]
The nginx controller inserts a few "X-" headers in the requests it sends to the pods. One of which is the "X-Format" header (`X-Format: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8` in my case) and that header seems to triggers the XML response from the error-pages container. 

The "X-Format" header is apparently based on the content of the "Accept" header in the request. Setting the accept header with curl to the same as the browser sends returns the XML reponse as well.

## Calling the pod directly, setting the X-Format header

```plain
$ curl -v -H 'X-Format: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' http://10.69.169.132:8080
*   Trying 10.69.169.132:8080...
* Connected to 10.69.169.132 (10.69.169.132) port 8080 (#0)
> GET / HTTP/1.1
> Host: 10.69.169.132:8080
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0
> Accept: */*
> X-Format: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Thu, 27 Jan 2022 22:56:29 GMT
< Content-Type: application/xml; charset=utf-8
< Content-Length: 424
< X-Robots-Tag: noindex
<
<?xml version="1.0" encoding="utf-8"?>
<error>
  <code>404</code>
  <message>Not Found</message>
  <description>The server can not find the requested page</description>
  <details>
    <originalURI></originalURI>
    <namespace></namespace>
    <ingressName></ingressName>
    <serviceName></serviceName>
    <servicePort></servicePort>
    <requestID></requestID>
    <timestamp>1643324190</timestamp>
  </details>
* Connection #0 to host 10.69.169.132 left intact
</error>
```

## Calling the ingress, setting the Accept header

```plain
$ curl -v -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' https://echo.private.domain/404
*   Trying 192.168.69.200:443...
* Connected to echo.private.domain (192.168.69.200) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=private.domain
*  start date: Jan  6 18:31:31 2022 GMT
*  expire date: Apr  6 18:31:30 2022 GMT
*  subjectAltName: host "echo.private.domain" matched cert's "*.private.domain"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x1fdcff0)
> GET /404 HTTP/2
> Host: echo.private.domain
> user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0
> accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 404
< date: Thu, 27 Jan 2022 23:29:44 GMT
< content-type: application/xml; charset=utf-8
< content-length: 481
< x-robots-tag: noindex
<
<?xml version="1.0" encoding="utf-8"?>
<error>
  <code>404</code>
  <message>Not Found</message>
  <description>The server can not find the requested page</description>
  <details>
    <originalURI>/404</originalURI>
    <namespace>tools</namespace>
    <ingressName>echoip</ingressName>
    <serviceName>echoip</serviceName>
    <servicePort>8080</servicePort>
    <requestID>40de3fd9a21e1c16a418cea7dd611cb1</requestID>
    <timestamp>1643326184</timestamp>
  </details>
* Connection #0 to host echo.private.domain left intact
</error>
```

You can add a netshoot container in the helm chart deployment (through `controller.extraContainers`) and you'll then be able to use e.g. `ngrep -W byline '' 'host <ip-of-defaultbackend-pod>'` to see the headers sent back and forth. 
Below are the headers sent from the nginx-controller (10.69.159.167) to the pod running the error-pages image (10.69.169.132) when accessing a non-existing page in the browser. 

```plain
####
T 10.69.159.167:50260 -> 10.69.169.132:8080 [AP] #14
GET / HTTP/1.0.
X-Code: 404.
X-Format: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8.
X-Original-URI: /404.
X-Namespace: tools.
X-Ingress-Name: echoip.
X-Service-Name: echoip.
X-Service-Port: 8080.
X-Request-ID: 1bd426ba590ffbcb2f00974d656c38fd.
Host: echo.private.domain.
Connection: close.
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0.
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8.
accept-language: en-US,en;q=0.5.
accept-encoding: gzip, deflate, br.
dnt: 1.
upgrade-insecure-requests: 1.
sec-fetch-dest: document.
sec-fetch-mode: navigate.
sec-fetch-site: none.
sec-fetch-user: ?1.
pragma: no-cache.
cache-control: no-cache.


##
T 10.69.169.132:8080 -> 10.69.159.167:50260 [AP] #16
HTTP/1.1 404 Not Found.
Date: Thu, 27 Jan 2022 22:11:03 GMT.
Content-Type: application/xml; charset=utf-8.
Content-Length: 481.
X-Robots-Tag: noindex.
Connection: close.

<?xml version="1.0" encoding="utf-8"?>
<error>
  <code>404</code>
  <message>Not Found</message>
  <description>The server can not find the requested page</description>
  <details>
    <originalURI>/404</originalURI>
    <namespace>tools</namespace>
    <ingressName>echoip</ingressName>
    <serviceName>echoip</serviceName>
    <servicePort>8080</servicePort>
    <requestID>1bd426ba590ffbcb2f00974d656c38fd</requestID>
    <timestamp>1643321463</timestamp>
  </details>
</error>
```

**Comment by tarampampam** [comment]
> The "X-Format" header is apparently based on the content of the "Accept" header in the request

Oh, rly?! Ok, challenge accepted! :D

**Comment by tarampampam** [comment]
Good news! You can test the fixed version right now, image `tarampampam/error-pages:ingress-test` was updated.

**Comment by onedr0p** [comment]
Just tested it and it works! Great job 👍

**Comment by tarampampam** [comment]
I'm very glad to hear that :)

**Comment by onedr0p** [comment]
Gonna go ahead and close this, thanks again!

**Comment by onedr0p** [comment]
If you don't want to wait in order to make a release soon, you can include this in the README.md

```
1. Set the `custom-http-errors` config value
2. Enable default backend
3. Set the default backend image

```yaml
controller:
  config:
    custom-http-errors: >-
      401,403,404,500,501,502,503
defaultBackend:
  enabled: true
  image:
    repository: ghcr.io/tarampampam/error-pages
    tag: latest
  # optional: change the default theme
  extraEnvs:
  - name: TEMPLATE_NAME
    value: l7-dark
```
```

**Comment by tarampampam** [comment]
I will wait for your PR

**Comment by onedr0p** [comment]
PR opened: https://github.com/tarampampam/error-pages/pull/53

**Comment by tarampampam** [comment]
:fire: [v2.4.0](https://github.com/tarampampam/error-pages/releases/tag/v2.4.0) released!
