### ISSUE TITLE
[Feature request] Switch to different error page after x time

### ISSUE THREAD

**Issue by modem7** [tarampampam/error-pages#48]
Would be fun if there was a way to switch to a different error page template after x amount of time (e.g. every 24 hours) when it's set to random.

**Comment by GoliathLabs** [comment]
That would be really nice. So we could see the beauty of each template after some time and users won't be bored with your error pages after a while😄.

**Comment by tarampampam** [comment]
Are you guys serious right now, or is this a joke? 😄

**Comment by modem7** [comment]
> Are you guys serious right now, or is this a joke? 😄 

Why not both?!

Nah, for me, I would genuinely like to have different ones without restarting the container cus I'm a lazy lazy sod!

**Comment by GoliathLabs** [comment]
Same here 😄

**Comment by ToshY** [comment]
I don't know if this may help, but you can actually create a config file to use a custom html template  ([see README](https://github.com/tarampampam/error-pages#usage)). Just generate the files and then mount them to your container . If you add some lovely JS to your custom template I think you can make it a lot more random/fun.

**Comment by modem7** [comment]
> I don't know if this may help, but you can actually create a config file to use a custom html template  ([see README](https://github.com/tarampampam/error-pages#usage)). Just generate the files and then mount them to your container . If you add some lovely JS to your custom template I think you can make it a lot more random/fun.

Yupper! But in this particular case, I have multiple templates that I would quite like to switch between, rather than a single template until container restart (utilising random).

**Comment by AlbanVidal** [comment]
Hi there,
For start, thanks @tarampampam for those templates, awesome! :)

Like the idea of this Issue, I wished to have different template for each load.
For that, I reorganizes the files (*Error_Numbre/Template.html*), and used `random_index` Nginx module.

I used the content of the `out` directory (see [Static error pages](https://github.com/tarampampam/error-pages/wiki/Static-error-pages)), localized in `/srv/http-errors` on my case, to generate tree **Error_Number/Template.html** on the `/srv/_all-http-errors/` directory:
```
cd /srv/http-errors
for file in $(find ./ -mindepth 2 -type f); do
    ERR_NO=$(echo $file|sed -E 's/.*\/([0-9]*).*/\1/')
    THEME=$(echo $file|sed -E 's/\.\/([a-z0-9-]*)\/.*/\1/')
    NEW_FILE="${ERR_NO}/${THEME}.html"
    mkdir -p ../_all-http-errors/$ERR_NO/
    cp -v $file ../_all-http-errors/${NEW_FILE}
done
# Output:
# './ghost/400.html' -> '../_all-http-errors/400/ghost.html'
# ...
# './noise/429.html' -> '../_all-http-errors/429/noise.html'
```

And then, here my Nginx configuration:
```
# Virtual host:
include /srv/http-errors/error_pages_content.conf;
location ~ /(10[0-3]|2[02][1-9]|30[1-8]|4[0125][0-9]|50[0-9])/ {
        root /srv/_all-http-errors;
        allow all;
        random_index on;
}

# /srv/http-errors/error_pages_content.conf
error_page 400 /400/;
error_page 401 /401/;
error_page 402 /402/;
error_page 403 /403/;
error_page 404 /404/;
error_page 405 /405/;
error_page 406 /406/;
error_page 407 /407/;
error_page 408 /408/;
error_page 409 /409/;
error_page 410 /410/;
error_page 411 /411/;
error_page 412 /412/;
error_page 413 /413/;
error_page 414 /414/;
error_page 415 /415/;
error_page 416 /416/;
error_page 417 /417/;
error_page 418 /418/;
error_page 421 /421/;
error_page 422 /422/;
error_page 423 /423/;
error_page 424 /424/;
error_page 425 /425/;
error_page 426 /426/;
error_page 428 /428/;
error_page 429 /429/;
error_page 431 /431/;
error_page 451 /451/;
error_page 500 /500/;
error_page 501 /501/;
error_page 502 /502/;
error_page 503 /503/;
error_page 504 /504/;
error_page 505 /505/;
error_page 506 /506/;
error_page 507 /507/;
error_page 508 /508/;
error_page 510 /510/;
error_page 511 /511/;
```

You can see examples with each error code on those URL:
+ https://www.zordhak.fr/404
+ ...
+ https://www.zordhak.fr/410
+ ...
+ https://www.zordhak.fr/500
+ ...

**Comment by tarampampam** [comment]
@modem7 I can implement a "special theme name" like a `random-daily` which will change the theme on a randomized only once per day? Or maybe you want to make it more frequent?

**Comment by modem7** [comment]
> @modem7 I can implement a "special theme name" like a `random-daily` which will change the theme on a randomized only once per day? Or maybe you want to make it more frequent?

That'd be perfect for my needs! Thank you!

**Comment by tarampampam** [comment]
[v2.6.0](https://github.com/tarampampam/error-pages/releases/tag/v2.6.0) released, now you can use `random-daily`/`random-hourly` - themes will be changed in random order once a day/hourly 🍻
