### ISSUE TITLE
random template

### ISSUE THREAD

**Issue by xpliz** [tarampampam/error-pages#6]
It would be a nice option to have and let generator pick random template from available ones? Or maybe specifying more than one in TEMPLATE_NAME and let it randomly pick from preselected templates. 

I'm libra and can't decide between ghost and shuffle ;)

**Comment by tarampampam** [comment]
Implemented in https://github.com/tarampampam/error-pages/releases/tag/v1.5.0

**Comment by SAOPP** [comment]
How did I manage to find out that the page is randomly generated only at the start of the container? Correct me if I'm wrong.

**Comment by tarampampam** [comment]
@SAOPP I'm sorry, but I can't understand you :(

**Comment by SAOPP** [comment]
I mean, random page choose only at start container right? Random error page is not randomize on every host request?

**Comment by tarampampam** [comment]
https://github.com/tarampampam/error-pages/blob/master/README.md#L93

you can use `random` (to use the randomized theme on server start) or `i-said-random` (to use the randomized template on **each request**)

**Comment by SAOPP** [comment]
Thank, I probably haven't finished reading this :)
