### ISSUE TITLE
X-Transmission-Session-id Header Stripped

### ISSUE THREAD

**Issue by jonwilliams84** [tarampampam/error-pages#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Great work on this project, it's certainly beautified my end users experience when they get an error however...

As transmission uses rpc to serve its pages to protect against CSRF it expects a valid session-id header in the request, otherwise it returns a 409 page. 

Without error-pages defined on the entrypoint in Traefik, the request hits the rpc endpoint and on the initial try it obtains a session-id and then retries resulting in a successful response and the page loads.

With error-pages defined, all consequent hits to the rpc endpoint result in a 409 as this error page strips the X-Transmission-Session-id header and therefore gets rejected.

Is there anyway of setting "Pass-through request/response headers" or an abilitiy to set a list of headers that are allowed to be kept?

Thanks in advance.

### Steps to reproduce

Logs: 

Without error-pages:
```
172.16.200.15 - - [20/Feb/2022:23:21:13 +0000] "POST /transmission/rpc HTTP/1.1" 409 593 "https://transmission.mydomain.com/transmission/web/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" "10.32.100.189"
172.16.200.3 - - [20/Feb/2022:23:21:15 +0000] "POST /transmission/rpc HTTP/1.1" 200 424 "-" "Python-urllib/3.9" "-"
172.16.200.3 - - [20/Feb/2022:23:21:15 +0000] "POST /transmission/rpc HTTP/1.1" 200 23925 "-" "Python-urllib/3.9" "-"
172.16.200.3 - - [20/Feb/2022:23:21:15 +0000] "POST /transmission/rpc HTTP/1.1" 200 1563 "-" "Python-urllib/3.9" "-"
```

With error-pages:
```
172.16.200.15 - - [20/Feb/2022:23:21:18 +0000] "POST /transmission/rpc HTTP/1.1" 409 593 "https://transmission.mydomain.com/transmission/web/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" "10.32.100.189"
172.16.200.15 - - [20/Feb/2022:23:21:23 +0000] "POST /transmission/rpc HTTP/1.1" 409 593 "https://transmission.mydomain.com/transmission/web/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" "10.32.100.189"
172.16.200.15 - - [20/Feb/2022:23:21:28 +0000] "POST /transmission/rpc HTTP/1.1" 409 593 "https://transmission.mydomain.com/transmission/web/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" "10.32.100.189"
172.16.200.15 - - [20/Feb/2022:23:21:33 +0000] "POST /transmission/rpc HTTP/1.1" 409 593 "https://transmission.mydomain.com/transmission/web/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" "10.32.100.189"
172.16.200.15 - - [20/Feb/2022:23:21:38 +0000] "POST /transmission/rpc HTTP/1.1" 409 593 "https://transmission.mydomain.com/transmission/web/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" "10.32.100.189"
```

**Comment by tarampampam** [comment]
Hi @jonwilliams84!

I think you should ask your question in the traefik community as most relevant.

**Comment by tarampampam** [comment]
Traefik community - https://community.traefik.io/

**Comment by jonwilliams84** [comment]
> Hi @jonwilliams84!
> 
> I think you should ask your question in the traefik community as most relevant.

It's not related to traefik though. If I create a custom error page in nginx and add config to allow the header described, it works fine.

**Comment by tarampampam** [comment]
Could you please show `nginx` configuration that works in your case as expected?

And anyway, I suppose that taking care of the proxying custom HTTP headers from the requests to the responses is out of this project's tasks (and it must be done at the layer above - that's why I said about the traefik community).

**Comment by tarampampam** [comment]
If you will not find options with the Traefik, please, check the changes in PR #67 - I believe this is exactly what you need.

After your feedback & tests, I will make a release with those changes 🤝

**Comment by tarampampam** [comment]
Docker image for a tests: `tarampampam/error-pages:proxy-headers`

Run it with passing environment variable `PROXY_HTTP_HEADERS=X-Transmission-Session-id`

**Comment by tarampampam** [comment]
Ping @jonwilliams84

**Comment by tarampampam** [comment]
Released in [v2.7.0](https://github.com/tarampampam/error-pages/releases/tag/v2.7.0)

**Comment by jonwilliams84** [comment]
Apologies...been flat out the past 2 days. I will test tonight, but thank you for the swift (potential) fix.

**Comment by jonwilliams84** [comment]
Hmmm....still not playing nice with transmission:

error-pages log:
```
{"level":"info","ts":1645645599.2564173,"msg":"HTTP request processed","useragent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.43","method":"GET","url":"/409.html","referer":"https://transmission.domain.com/transmission/web/","status_code":200,"content_type":"text/html; charset=utf-8","connection_close":false,"duration":0.00021726,"request_headers":["Host: transmission.domain.com","Content-Type: text/plain;charset=UTF-8","User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.43","Cookie: _forward_auth=redacted=|redacted|redacted@gmail.com","Accept: */*","Accept-Encoding: gzip, deflate, br","Accept-Language: en-GB,en;q=0.9,en-US;q=0.8","Dnt: 1","Origin: https://transmission.domain.com","Referer: https://transmission.sirfragalot.com/transmission/web/","Sec-Ch-Ua: \" Not A;Brand\";v=\"99\", \"Chromium\";v=\"98\", \"Microsoft Edge\";v=\"98\"","Sec-Ch-Ua-Mobile: ?0","Sec-Ch-Ua-Platform: \"macOS\"","Sec-Fetch-Dest: empty","Sec-Fetch-Mode: cors","Sec-Fetch-Site: same-origin","X-Forwarded-Host: transmission.domain.com","X-Forwarded-Port: 443","X-Forwarded-Proto: https","X-Forwarded-Server: redacted","X-Forwarded-User: redacted@gmail.com","X-Real-Ip: re.da.ct.ed","X-Transmission-Session-Id: null"],"response_headers":["Content-Type: text/html; charset=utf-8","X-Robots-Tag: noindex","X-Transmission-Session-Id: null"]}
```

Here is an nginx config that is working with transmission:
```
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    error_page  500 502 503 504  /50x.html;

    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location / {
        proxy_read_timeout 300;
        proxy_pass_header  X-Transmission-Session-Id;
        proxy_set_header   X-Forwarded-Host $host;
        proxy_set_header   X-Forwarded-Server $host;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass         http://transmission:9091;
    }
}
```

**Comment by tarampampam** [comment]
Oh, your nginx works as a proxy server, and not as an HTTP service for the error pages only... Why you didn't say it before?

As you can see the header `X-Transmission-Session-Id` proxied as expected, but I have no idea how to help you, sorry 😞

If (when) you find the solution, please, tell me.

**Comment by jonwilliams84** [comment]
Apologies, I should have been clearer around nginx.

No worries, thank you for looking into it. For now I will just have the 409 error unhandled.
`- "traefik.http.middlewares.error-pages-middleware.errors.status=400-408,410-599"`

Regards,

Jon
