### ISSUE TITLE
add extra template

### ISSUE THREAD

**Issue by RHITNL** [tarampampam/error-pages#8]
Hi,

Thank you for this simple docker container. I use it with Traefik and it works flawless.
I used another before (very simular to this thought) which has antoher template called "noise"
How can I add this to this repo? I tried to add template, updated tests.yml to add folder and did a docker build. 

`Step 9/16 : RUN ./generator/generator.js -c ./config.json -o ./out
 ---> Running in 08d7c027a654
SyntaxError: Unexpected token { in JSON at position 422
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/src/generator/generator.js:32:32)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
The command '/bin/sh -c ./generator/generator.js -c ./config.json -o ./out' returned a non-zero code: 1`

I need to say, I'm new to building docker images (but running docker containers for quit some time now) and I'm not a programmer 
Can you help me out building it or how to add this template to this repo.

Thanks you for your reply,

Ralph

**Comment by tarampampam** [comment]
Hi @RHITNL!

Adding a new template is very easy, you can follow these steps:

- Make a fork of this repository
- Create file `noise.html` in directory `./templates` with your template content (look in other templates for examples, you could use special patterns `{{ code }}`, `{{ message }}` and `{{ description }}`)
- Append in `./config.json` the following lines:

```json
{
    "templates": [
        // ...
        {
            "name": "noise",
            "path": "./templates/noise.html"
        }
    ],
    // ...
}
```

- Build local docker image (`docker build -f ./Dockerfile -t error-pages:local .`) or make a PR with your changes into this repository, and your template will be included in the "original" (`tarampampam/error-pages`) docker image ;)

**Comment by RHITNL** [comment]
Hi @tarampampam ,

thanks for helping me out. I was doing the right thing but made a typo. I build the image just fine now with this update :) Hope you like it.
 https://github.com/tarampampam/error-pages/pull/9#issue-620214180

Regards,

Ralph

**Comment by tarampampam** [comment]
Released in https://github.com/tarampampam/error-pages/releases/tag/v1.6.0
