### ISSUE TITLE
Use numeric user id to be compatible with Kubernetes Pod Security Policies

### ISSUE THREAD

**Issue by GoliathLabs** [tarampampam/error-pages#92]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] And it has nothing to do with Traefik

### Describe the bug

Non-numeric users don't go well with the pod security policies of kubernetes

### Steps to reproduce

/

### Configuration files

```yaml
/
```

### Relevant log output

```shell
/
```

### Anything else?

This might be useful for futher reference: https://github.com/CollaboraOnline/online/blob/master/docker/from-source/Debian

**Comment by tarampampam** [comment]
Hi! What I should to do? What is your suggestion?

**Comment by GoliathLabs** [comment]
The dockerfile I've referenced does this quite nicely. Instead of using an actual username going with a numeric one (e.g. 1001) should do the job

**Comment by tarampampam** [comment]
Changes in #93 are enough for this?

**Comment by GoliathLabs** [comment]
@tarampampam Sorry for replying so late, I didn't see the new comment.

Your PR should do the job nicely

**Comment by tarampampam** [comment]
:fire: [v2.13.0 released](https://github.com/tarampampam/error-pages/releases/tag/v2.13.0)

**Comment by GoliathLabs** [comment]
@tarampampam wohoo! Nice work. Thanks.

Did already deploy the newest version on my systems :)
